export const currencies = [
  // --- FIAT CURRENCIES ---
  { code: 'USD', name: 'US Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/us.svg' },
  { code: 'EUR', name: 'Euro', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/eu.svg' },
  { code: 'GBP', name: 'British Pound', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/gb.svg' },
  { code: 'CAD', name: 'Canadian Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ca.svg' },
  { code: 'AUD', name: 'Australian Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/au.svg' },
  { code: 'JPY', name: 'Japanese Yen', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/jp.svg' },
  { code: 'CHF', name: 'Swiss Franc', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ch.svg' },
  { code: 'SEK', name: 'Swedish Krona', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/se.svg' },
  { code: 'NZD', name: 'New Zealand Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/nz.svg' },
  { code: 'SGD', name: 'Singapore Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/sg.svg' },
  { code: 'HKD', name: 'Hong Kong Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/hk.svg' },
  { code: 'NOK', name: 'Norwegian Krone', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/no.svg' },
  { code: 'DKK', name: 'Danish Krone', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/dk.svg' },
  { code: 'PLN', name: 'Polish Zloty', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/pl.svg' },
  { code: 'CZK', name: 'Czech Koruna', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/cz.svg' },
  { code: 'HUF', name: 'Hungarian Forint', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/hu.svg' },
  { code: 'RON', name: 'Romanian Leu', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ro.svg' },
  { code: 'BGN', name: 'Bulgarian Lev', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/bg.svg' },
  { code: 'HRK', name: 'Croatian Kuna', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/hr.svg' },
  { code: 'RUB', name: 'Russian Ruble', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ru.svg' },
  { code: 'TRY', name: 'Turkish Lira', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/tr.svg' },
  { code: 'BRL', name: 'Brazilian Real', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/br.svg' },
  { code: 'MXN', name: 'Mexican Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/mx.svg' },
  { code: 'ARS', name: 'Argentine Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ar.svg' },
  { code: 'CLP', name: 'Chilean Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/cl.svg' },
  { code: 'COP', name: 'Colombian Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/co.svg' },
  { code: 'PEN', name: 'Peruvian Sol', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/pe.svg' },
  { code: 'UYU', name: 'Uruguayan Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/uy.svg' },
  { code: 'ZAR', name: 'South African Rand', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/za.svg' },
  { code: 'NGN', name: 'Nigerian Naira', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ng.svg' },
  { code: 'GHS', name: 'Ghanaian Cedi', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/gh.svg' },
  { code: 'KES', name: 'Kenyan Shilling', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ke.svg' },
  { code: 'UGX', name: 'Ugandan Shilling', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ug.svg' },
  { code: 'TZS', name: 'Tanzanian Shilling', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/tz.svg' },
  { code: 'XOF', name: 'West African CFA', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/xof.svg' },
  { code: 'XAF', name: 'Central African CFA', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/xaf.svg' },
  { code: 'ZMW', name: 'Zambian Kwacha', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/zm.svg' },
  { code: 'KWD', name: 'Kuwaiti Dinar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/kw.svg' },
  { code: 'AED', name: 'UAE Dirham', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ae.svg' },
  { code: 'SAR', name: 'Saudi Riyal', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/sa.svg' },
  { code: 'QAR', name: 'Qatari Riyal', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/qa.svg' },
  { code: 'BHD', name: 'Bahraini Dinar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/bh.svg' },
  { code: 'OMR', name: 'Omani Rial', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/om.svg' },
  { code: 'JOD', name: 'Jordanian Dinar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/jo.svg' },
  { code: 'ILS', name: 'Israeli Shekel', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/il.svg' },
  { code: 'EGP', name: 'Egyptian Pound', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/eg.svg' },
  { code: 'LBP', name: 'Lebanese Pound', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/lb.svg' },
  { code: 'KRW', name: 'South Korean Won', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/kr.svg' },
  { code: 'CNY', name: 'Chinese Yuan', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/cn.svg' },
  { code: 'INR', name: 'Indian Rupee', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/in.svg' },
  { code: 'PKR', name: 'Pakistani Rupee', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/pk.svg' },
  { code: 'BDT', name: 'Bangladeshi Taka', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/bd.svg' },
  { code: 'LKR', name: 'Sri Lankan Rupee', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/lk.svg' },
  { code: 'NPR', name: 'Nepalese Rupee', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/np.svg' },
  { code: 'MMK', name: 'Myanmar Kyat', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/mm.svg' },
  { code: 'THB', name: 'Thai Baht', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/th.svg' },
  { code: 'VND', name: 'Vietnamese Dong', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/vn.svg' },
  { code: 'IDR', name: 'Indonesian Rupiah', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/id.svg' },
  { code: 'MYR', name: 'Malaysian Ringgit', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/my.svg' },
  { code: 'PHP', name: 'Philippine Peso', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/ph.svg' },
  { code: 'TWD', name: 'Taiwan Dollar', type: 'fiat', icon: 'https://hatscripts.github.io/circle-flags/flags/tw.svg' },

  // --- CRYPTO CURRENCIES ---
  // Major Coins
  { code: 'BTC', name: 'Bitcoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.svg' },
  { code: 'ETH', name: 'Ethereum', type: 'crypto', icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg' },
  { code: 'USDT', name: 'Tether', type: 'crypto', icon: 'https://cryptologos.cc/logos/tether-usdt-logo.svg' },
  { code: 'USDC', name: 'USD Coin', type: 'crypto', icon: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.svg' },
  { code: 'BNB', name: 'BNB', type: 'crypto', icon: 'https://cryptologos.cc/logos/bnb-bnb-logo.svg' },
  { code: 'XRP', name: 'XRP', type: 'crypto', icon: 'https://cryptologos.cc/logos/xrp-xrp-logo.svg' },
  { code: 'SOL', name: 'Solana', type: 'crypto', icon: 'https://cryptologos.cc/logos/solana-sol-logo.svg' },
  { code: 'DOGE', name: 'Dogecoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/dogecoin-doge-logo.svg' },
  { code: 'ADA', name: 'Cardano', type: 'crypto', icon: 'https://cryptologos.cc/logos/cardano-ada-logo.svg' },
  { code: 'TRX', name: 'TRON', type: 'crypto', icon: 'https://cryptologos.cc/logos/tron-trx-logo.svg' },
  { code: 'AVAX', name: 'Avalanche', type: 'crypto', icon: 'https://cryptologos.cc/logos/avalanche-avax-logo.svg' },
  { code: 'TON', name: 'Toncoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/toncoin-ton-logo.svg' },
  { code: 'SHIB', name: 'Shiba Inu', type: 'crypto', icon: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.svg' },
  { code: 'DOT', name: 'Polkadot', type: 'crypto', icon: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.svg' },
  { code: 'LINK', name: 'Chainlink', type: 'crypto', icon: 'https://cryptologos.cc/logos/chainlink-link-logo.svg' },
  { code: 'MATIC', name: 'Polygon', type: 'crypto', icon: 'https://cryptologos.cc/logos/polygon-matic-logo.svg' },
  { code: 'LTC', name: 'Litecoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/litecoin-ltc-logo.svg' },
  { code: 'UNI', name: 'Uniswap', type: 'crypto', icon: 'https://cryptologos.cc/logos/uniswap-uni-logo.svg' },
  { code: 'BCH', name: 'Bitcoin Cash', type: 'crypto', icon: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.svg' },
  { code: 'ATOM', name: 'Cosmos', type: 'crypto', icon: 'https://cryptologos.cc/logos/cosmos-atom-logo.svg' },
  { code: 'XLM', name: 'Stellar', type: 'crypto', icon: 'https://cryptologos.cc/logos/stellar-xlm-logo.svg' },
  { code: 'ETC', name: 'Ethereum Classic', type: 'crypto', icon: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.svg' },
  { code: 'HBAR', name: 'Hedera', type: 'crypto', icon: 'https://cryptologos.cc/logos/hedera-hbar-logo.svg' },
  { code: 'XMR', name: 'Monero', type: 'crypto', icon: 'https://cryptologos.cc/logos/monero-xmr-logo.svg' },
  { code: 'FIL', name: 'Filecoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/filecoin-fil-logo.svg' },
  { code: 'ALGO', name: 'Algorand', type: 'crypto', icon: 'https://cryptologos.cc/logos/algorand-algo-logo.svg' },
  { code: 'NEAR', name: 'NEAR Protocol', type: 'crypto', icon: 'https://cryptologos.cc/logos/near-protocol-near-logo.svg' },
  { code: 'VET', name: 'VeChain', type: 'crypto', icon: 'https://cryptologos.cc/logos/vechain-vet-logo.svg' },
  { code: 'AAVE', name: 'Aave', type: 'crypto', icon: 'https://cryptologos.cc/logos/aave-aave-logo.svg' },
  { code: 'GRT', name: 'The Graph', type: 'crypto', icon: 'https://cryptologos.cc/logos/the-graph-grt-logo.svg' },
  { code: 'MANA', name: 'Decentraland', type: 'crypto', icon: 'https://cryptologos.cc/logos/decentraland-mana-logo.svg' },
  { code: 'SAND', name: 'The Sandbox', type: 'crypto', icon: 'https://cryptologos.cc/logos/the-sandbox-sand-logo.svg' },
  { code: 'AXS', name: 'Axie Infinity', type: 'crypto', icon: 'https://cryptologos.cc/logos/axie-infinity-axs-logo.svg' },
  { code: 'APE', name: 'ApeCoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/apecoin-ape-logo.svg' },
  { code: 'FTM', name: 'Fantom', type: 'crypto', icon: 'https://cryptologos.cc/logos/fantom-ftm-logo.svg' },
  { code: 'THETA', name: 'Theta Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/theta-network-theta-logo.svg' },
  { code: 'XTZ', name: 'Tezos', type: 'crypto', icon: 'https://cryptologos.cc/logos/tezos-xtz-logo.svg' },
  { code: 'FLOW', name: 'Flow', type: 'crypto', icon: 'https://cryptologos.cc/logos/flow-flow-logo.svg' },
  { code: 'CHZ', name: 'Chiliz', type: 'crypto', icon: 'https://cryptologos.cc/logos/chiliz-chz-logo.svg' },
  { code: 'ENJ', name: 'Enjin Coin', type: 'crypto', icon: 'https://cryptologos.cc/logos/enjin-coin-enj-logo.svg' },
  { code: 'CRV', name: 'Curve DAO Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.svg' },
  { code: 'SNX', name: 'Synthetix', type: 'crypto', icon: 'https://cryptologos.cc/logos/synthetix-snx-logo.svg' },
  { code: '1INCH', name: '1inch Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/1inch-1inch-logo.svg' },
  { code: 'BAT', name: 'Basic Attention Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.svg' },
  { code: 'COMP', name: 'Compound', type: 'crypto', icon: 'https://cryptologos.cc/logos/compound-comp-logo.svg' },
  { code: 'MKR', name: 'Maker', type: 'crypto', icon: 'https://cryptologos.cc/logos/maker-mkr-logo.svg' },
  { code: 'YFI', name: 'yearn.finance', type: 'crypto', icon: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.svg' },
  { code: 'ZRX', name: '0x', type: 'crypto', icon: 'https://cryptologos.cc/logos/0x-zrx-logo.svg' },
  { code: 'OMG', name: 'OMG Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/omg-network-omg-logo.svg' },
  { code: 'BNT', name: 'Bancor', type: 'crypto', icon: 'https://cryptologos.cc/logos/bancor-bnt-logo.svg' },
  { code: 'LRC', name: 'Loopring', type: 'crypto', icon: 'https://cryptologos.cc/logos/loopring-lrc-logo.svg' },
  { code: 'KNC', name: 'Kyber Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/kyber-network-knc-logo.svg' },
  { code: 'REN', name: 'Ren', type: 'crypto', icon: 'https://cryptologos.cc/logos/ren-ren-logo.svg' },
  { code: 'BAL', name: 'Balancer', type: 'crypto', icon: 'https://cryptologos.cc/logos/balancer-bal-logo.svg' },
  { code: 'UMA', name: 'UMA', type: 'crypto', icon: 'https://cryptologos.cc/logos/uma-uma-logo.svg' },
  { code: 'NMR', name: 'Numeraire', type: 'crypto', icon: 'https://cryptologos.cc/logos/numeraire-nmr-logo.svg' },

  // Layer 2 / Scaling
  { code: 'ARB', name: 'Arbitrum', type: 'crypto', icon: 'https://cryptologos.cc/logos/arbitrum-arb-logo.svg' },
  { code: 'OP', name: 'Optimism', type: 'crypto', icon: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.svg' },
  { code: 'IMX', name: 'Immutable X', type: 'crypto', icon: 'https://cryptologos.cc/logos/immutable-x-imx-logo.svg' },

  // Stablecoins
  { code: 'DAI', name: 'Dai', type: 'crypto', icon: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg' },
  { code: 'BUSD', name: 'Binance USD', type: 'crypto', icon: 'https://cryptologos.cc/logos/binance-usd-busd-logo.svg' },
  { code: 'TUSD', name: 'TrueUSD', type: 'crypto', icon: 'https://cryptologos.cc/logos/trueusd-tusd-logo.svg' },
  { code: 'USDP', name: 'Pax Dollar', type: 'crypto', icon: 'https://cryptologos.cc/logos/paxos-standard-pax-logo.svg' },
  { code: 'GUSD', name: 'Gemini Dollar', type: 'crypto', icon: 'https://cryptologos.cc/logos/gemini-dollar-gusd-logo.svg' },
  { code: 'EURC', name: 'Euro Coin', type: 'crypto', icon: 'https://cryptologos.cc/logos/euro-coin-eurc-logo.svg' },

  // DeFi Tokens
  { code: 'SUSHI', name: 'SushiSwap', type: 'crypto', icon: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.svg' },
  { code: 'CAKE', name: 'PancakeSwap', type: 'crypto', icon: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.svg' },
  { code: 'CVX', name: 'Convex Finance', type: 'crypto', icon: 'https://cryptologos.cc/logos/convex-finance-cvx-logo.svg' },
  { code: 'LDO', name: 'Lido DAO', type: 'crypto', icon: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.svg' },
  { code: 'RPL', name: 'Rocket Pool', type: 'crypto', icon: 'https://cryptologos.cc/logos/rocket-pool-eth-rpl-logo.svg' },
  { code: 'ANKR', name: 'Ankr', type: 'crypto', icon: 'https://cryptologos.cc/logos/ankr-ankr-logo.svg' },
  { code: 'STX', name: 'Stacks', type: 'crypto', icon: 'https://cryptologos.cc/logos/stacks-stx-logo.svg' },

  // Infrastructure
  { code: 'ICP', name: 'Internet Computer', type: 'crypto', icon: 'https://cryptologos.cc/logos/internet-computer-icp-logo.svg' },
  { code: 'APT', name: 'Aptos', type: 'crypto', icon: 'https://cryptologos.cc/logos/aptos-apt-logo.svg' },
  { code: 'SUI', name: 'Sui', type: 'crypto', icon: 'https://cryptologos.cc/logos/sui-sui-logo.svg' },
  { code: 'SEI', name: 'Sei', type: 'crypto', icon: 'https://cryptologos.cc/logos/sei-sei-logo.svg' },
  { code: 'MINA', name: 'Mina Protocol', type: 'crypto', icon: 'https://cryptologos.cc/logos/mina-mina-logo.svg' },
  { code: 'ROSE', name: 'Oasis Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/oasis-network-rose-logo.svg' },
  { code: 'GLMR', name: 'Moonbeam', type: 'crypto', icon: 'https://cryptologos.cc/logos/moonbeam-glmr-logo.svg' },
  { code: 'MOVR', name: 'Moonriver', type: 'crypto', icon: 'https://cryptologos.cc/logos/moonriver-movr-logo.svg' },
  { code: 'ASTR', name: 'Astar', type: 'crypto', icon: 'https://cryptologos.cc/logos/astar-astr-logo.svg' },
  { code: 'ACA', name: 'Acala Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/acala-aca-logo.svg' },

  // Gaming
  { code: 'ILV', name: 'Illuvium', type: 'crypto', icon: 'https://cryptologos.cc/logos/illuvium-ilv-logo.svg' },
  { code: 'GALA', name: 'Gala', type: 'crypto', icon: 'https://cryptologos.cc/logos/gala-gala-logo.svg' },
  { code: 'MAGIC', name: 'MAGIC', type: 'crypto', icon: 'https://cryptologos.cc/logos/magic-magic-logo.svg' },
  { code: 'GMT', name: 'STEPN', type: 'crypto', icon: 'https://cryptologos.cc/logos/stepn-gmt-logo.svg' },
  { code: 'VOXEL', name: 'Voxies', type: 'crypto', icon: 'https://cryptologos.cc/logos/voxies-voxel-logo.svg' },
  { code: 'UOS', name: 'Ultra', type: 'crypto', icon: 'https://cryptologos.cc/logos/ultra-uos-logo.svg' },
  { code: 'TLM', name: 'Alien Worlds', type: 'crypto', icon: 'https://cryptologos.cc/logos/alien-worlds-tlm-logo.svg' },

  // Privacy
  { code: 'ZEC', name: 'Zcash', type: 'crypto', icon: 'https://cryptologos.cc/logos/zcash-zec-logo.svg' },
  { code: 'DASH', name: 'Dash', type: 'crypto', icon: 'https://cryptologos.cc/logos/dash-dash-logo.svg' },

  // Storage
  { code: 'SC', name: 'Siacoin', type: 'crypto', icon: 'https://cryptologos.cc/logos/siacoin-sc-logo.svg' },
  { code: 'STORJ', name: 'Storj', type: 'crypto', icon: 'https://cryptologos.cc/logos/storj-storj-logo.svg' },
  { code: 'AR', name: 'Arweave', type: 'crypto', icon: 'https://cryptologos.cc/logos/arweave-ar-logo.svg' },
  { code: 'HOT', name: 'Holo', type: 'crypto', icon: 'https://cryptologos.cc/logos/holo-hot-logo.svg' },
  { code: 'IOTX', name: 'IoTeX', type: 'crypto', icon: 'https://cryptologos.cc/logos/iotex-iotx-logo.svg' },

  // Oracles
  { code: 'BAND', name: 'Band Protocol', type: 'crypto', icon: 'https://cryptologos.cc/logos/band-protocol-band-logo.svg' },
  { code: 'TRB', name: 'Tellor', type: 'crypto', icon: 'https://cryptologos.cc/logos/tellor-trb-logo.svg' },
  { code: 'API3', name: 'API3', type: 'crypto', icon: 'https://cryptologos.cc/logos/api3-api3-logo.svg' },

  // Meme Coins
  { code: 'PEPE', name: 'Pepe', type: 'crypto', icon: 'https://cryptologos.cc/logos/pepe-pepe-logo.svg' },
  { code: 'FLOKI', name: 'Floki Inu', type: 'crypto', icon: 'https://cryptologos.cc/logos/floki-inu-floki-logo.svg' },
  { code: 'BONK', name: 'Bonk', type: 'crypto', icon: 'https://cryptologos.cc/logos/bonk1-bonk-logo.svg' },

  // Exchange Tokens
  { code: 'CRO', name: 'Cronos', type: 'crypto', icon: 'https://cryptologos.cc/logos/cronos-cro-logo.svg' },
  { code: 'FTT', name: 'FTX Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/ftx-token-ftt-logo.svg' },
  { code: 'KCS', name: 'KuCoin Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/kucoin-token-kcs-logo.svg' },
  { code: 'HT', name: 'Huobi Token', type: 'crypto', icon: 'https://cryptologos.cc/logos/huobi-token-ht-logo.svg' },
  { code: 'GT', name: 'GateToken', type: 'crypto', icon: 'https://cryptologos.cc/logos/gatetoken-gt-logo.svg' },
  { code: 'LEO', name: 'UNUS SED LEO', type: 'crypto', icon: 'https://cryptologos.cc/logos/unus-sed-leo-leo-logo.svg' },
  { code: 'OKB', name: 'OKB', type: 'crypto', icon: 'https://cryptologos.cc/logos/okb-okb-logo.svg' },

  // Others
  { code: 'WEMIX', name: 'WEMIX', type: 'crypto', icon: 'https://cryptologos.cc/logos/wemix-wemix-logo.svg' },
  { code: 'BIT', name: 'BitDAO', type: 'crypto', icon: 'https://cryptologos.cc/logos/bitdao-bit-logo.svg' },
  { code: 'ENS', name: 'Ethereum Name Service', type: 'crypto', icon: 'https://cryptologos.cc/logos/ethereum-name-service-ens-logo.svg' },
  { code: 'DNT', name: 'district0x', type: 'crypto', icon: 'https://cryptologos.cc/logos/district0x-dnt-logo.svg' },
  { code: 'ANT', name: 'Aragon', type: 'crypto', icon: 'https://cryptologos.cc/logos/aragon-ant-logo.svg' },
  { code: 'GNO', name: 'Gnosis', type: 'crypto', icon: 'https://cryptologos.cc/logos/gnosis-gno-logo.svg' },
  { code: 'MLN', name: 'Enzyme', type: 'crypto', icon: 'https://cryptologos.cc/logos/enzyme-mln-logo.svg' },
  { code: 'REP', name: 'Augur', type: 'crypto', icon: 'https://cryptologos.cc/logos/augur-rep-logo.svg' },
  { code: 'NU', name: 'NuCypher', type: 'crypto', icon: 'https://cryptologos.cc/logos/nucypher-nu-logo.svg' },
  { code: 'KEEP', name: 'Keep Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/keep-network-keep-logo.svg' },
  { code: 'T', name: 'Threshold', type: 'crypto', icon: 'https://cryptologos.cc/logos/threshold-t-logo.svg' },
  { code: 'CVC', name: 'Civic', type: 'crypto', icon: 'https://cryptologos.cc/logos/civic-cvc-logo.svg' },
  { code: 'SKL', name: 'SKALE', type: 'crypto', icon: 'https://cryptologos.cc/logos/skale-skl-logo.svg' },
  { code: 'CELR', name: 'Celer Network', type: 'crypto', icon: 'https://cryptologos.cc/logos/celer-network-celr-logo.svg' },
  { code: 'FET', name: 'Fetch.ai', type: 'crypto', icon: 'https://cryptologos.cc/logos/fetch-fet-logo.svg' },
  { code: 'AGIX', name: 'SingularityNET', type: 'crypto', icon: 'https://cryptologos.cc/logos/singularitynet-agix-logo.svg' },
  { code: 'OCEAN', name: 'Ocean Protocol', type: 'crypto', icon: 'https://cryptologos.cc/logos/ocean-protocol-ocean-logo.svg' },
  { code: 'RLC', name: 'iExec RLC', type: 'crypto', icon: 'https://cryptologos.cc/logos/iexec-rlc-rlc-logo.svg' },
  { code: 'NKN', name: 'NKN', type: 'crypto', icon: 'https://cryptologos.cc/logos/nkn-nkn-logo.svg' },
  { code: 'HIVE', name: 'Hive', type: 'crypto', icon: 'https://cryptologos.cc/logos/hive-blockchain-hive-logo.svg' },
  { code: 'STEEM', name: 'Steem', type: 'crypto', icon: 'https://cryptologos.cc/logos/steem-steem-logo.svg' },
  { code: 'SBD', name: 'Steem Dollars', type: 'crypto', icon: 'https://cryptologos.cc/logos/steem-dollars-sbd-logo.svg' },
  { code: 'BLZ', name: 'Bluzelle', type: 'crypto', icon: 'https://cryptologos.cc/logos/bluzelle-blz-logo.svg' },
  { code: 'CTSI', name: 'Cartesi', type: 'crypto', icon: 'https://cryptologos.cc/logos/cartesi-ctsi-logo.svg' },
  { code: 'REQ', name: 'Request', type: 'crypto', icon: 'https://cryptologos.cc/logos/request-req-logo.svg' },
  { code: 'POWR', name: 'Power Ledger', type: 'crypto', icon: 'https://cryptologos.cc/logos/power-ledger-powr-logo.svg' },
  { code: 'MCO', name: 'MCO', type: 'crypto', icon: 'https://cryptologos.cc/logos/mco-mco-logo.svg' },
  { code: 'USDK', name: 'USDK', type: 'crypto', icon: 'https://cryptologos.cc/logos/usdk-usdk-logo.svg' },
  { code: 'SAI', name: 'Single Collateral DAI', type: 'crypto', icon: 'https://cryptologos.cc/logos/single-collateral-dai-sai-logo.svg' },
];